POST http://localhost:3003/classRom
Content-Type: application/json

{
    "nome":"Jackson",
    "modulo": 5 
}

###

GET http://localhost:3003/classRom
Content-Type: application/json

###
PUT http://localhost:3003/classRom/1656036223892
Content-Type: application/json

{
    "modulo": 1
}

###

POST http://localhost:3003/student
Content-Type: application/json

{
    "nome": "Luian",
    "email": "luiandapisadinha@gmail.com",
    "data_nasc": "1999/02/12",
    "turma_id": "1655927633690"
}

###

GET http://localhost:3003/estudante
Content-Type: application/json

###

PUT http://localhost:3003/estudante/1655994505513
Content-Type: application/json

{
    "turma_id": ""
}

###
POST http://localhost:3003/docente
Content-Type: application/json

{
    "nome": "",
    "email": "", 
    "data_nasc": "",
    "turma_id": ""
}

###

GET http://localhost:3003/docente
Content-Type: application/json

###

PUT http://localhost:3003/docente/1655994199165
Content-Type: application/json

{
    "turma_id": ""
}
###

POST http://localhost:3003/especialidade
Content-Type: application/json

{
    "nome":"React"
}

###

POST http://localhost:3003/hobby
Content-Type: application/json

{
    "nome":"Jogar"
}

###
POST http://localhost:3003/especialidade-docente
Content-Type: application/json

{
    "docente_id":"1656011767851",
    "especialidade_id":"1656017815996"
}

###
POST http://localhost:3003/hobby-estudante
Content-Type: application/json

{
    "estudante_id":"1655994505513",
    "hobby_id":"1656036926393"
}



